version: '3.2'

services:

  vue-build:
    build:
      context: ../
      dockerfile: ./docker-syohomoto-spring-dev/dockerfile_vue
    image: syohomoto-dev-vue
    container_name: syohomoto-SpringVueBuild
    volumes:
       - ../workspace:/workspace
    tty: true
