version: '3.2'

services:

  vue-build:
    build:
      context: ../
      dockerfile: ./docker-syohomoto-spring-dev/dockerfile_vue
    image: syohomoto-dev-vue
    container_name: syohomoto-SpringVueBuild
    volumes:
       - ../workspace:/workspace
    tty: true

  spring-build:
    build:
      context: ../
      dockerfile: ./docker-syohomoto-spring-dev/dockerfile_web_build
    image: syohomoto-dev-spring-build
    container_name: syohomoto-SpringBuildWeb
    # マウント先SpringBootプロジェクトへVueでビルドした静的ファイルをコピー
    command: bash -c "rm -rf /workspace/api/shoho/src/main/resources/static/assets/* &&
                      rm -f /workspace/api/shoho/src/main/resources/templates/*.html &&
                      cp -rp -f /usr/workspace/api/shoho/src/main/resources/static/assets /workspace/api/shoho/src/main/resources/static/ && 
                      cp -f /usr/workspace/api/shoho/src/main/resources/templates/*.html /workspace/api/shoho/src/main/resources/templates/ &&
                      /bin/bash"
    volumes:
       - ../workspace:/workspace
    tty: true
    ports: 
      - 8080:8080
