# 測試環境配置
spring:
  profiles:
    active: test
  
  # 測試環境日誌配置
logging:
  level:
    com.collaboportal.common.spring.common: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 測試環境特定配置
test:
  auth:
    enabled: true
    no-authorization: "0"  # 測試環境允許無認證
    env-flag: "1"          # 測試環境標識
    no-auth-url: "/health,/error,/static/**,/favicon.ico,/testEnv" 