version: '3.2'

services:

  shoho-spring:
  # 指定したコンテキストより上のフォルダは見えないので、上のフォルダが見れるようにコンテキストを上にしている
    build:
      context: .
      dockerfile: dockerfile_build_api
    image: shoho-spring
    container_name: shohoSpringBuild
    volumes:
       - ../workspace:/home/workspace
    tty: true
  
networks:
  default:
    name: docker-dev_default
    external: true

